In [1]:
import pandas as pd

In [2]:
col_names = ['date', 'game_type', 'home_team', 'h_id', 'game_result', 'game_id', 'away_team', 'a_id']
logfile = pd.read_csv('raw_data/HA_season_games_log.csv', names=col_names)

In [4]:
logfile
# bad parsed file

,date,game_type,home_team,h_id,game_result,game_id,away_team,a_id
0,23.06 - 21:00,Friendly,HC Jelgava Stars,['team_id=42152'],4:1,['match_id=897060599'],FireStorm,['team_id=10056']
1,Tactical points offense 5 defense 5,00:00,NaN,NaN,NaN,NaN,NaN,NaN
2,"Francis Taukulis - 1:0 (Niks Silmacis, Staņisl...",03:09,NaN,NaN,NaN,NaN,NaN,NaN
3,penalty player - Edmunds Bambergs4 on 5,08:04,NaN,NaN,NaN,NaN,NaN,NaN
4,Tactical points offense 5 defense 5,20:00,NaN,NaN,NaN,NaN,NaN,NaN
5,Lucas McDonald - 2:0 (perfect pass Juris Norītis),20:16,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,27:00,penalty player - 4 on 5,NaN,NaN,NaN,NaN,NaN
7,Lucas McDonald - 3:0 PPrebound(poor pass Edmun...,28:04,NaN,NaN,NaN,NaN,NaN,NaN
8,penalty player - Raimonds Ķiploks4 on 5,29:04,NaN,NaN,NaN,NaN,NaN,NaN
9,penalty player - Osvalds Jākabsons4 on 5,34:07,NaN,NaN,NaN,NaN,NaN,NaN
10,Tactical points offense 5 defense 5,40:00,NaN,NaN,NaN,NaN,NaN,NaN
11,penalty player - Edmunds Bambergs4 on 5,52:09,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,52:41,Max Miilunpohja - 3:1 PPrebound(poor pass Panu...,NaN,NaN,NaN,NaN,NaN
13,Raimonds Ķiploks - 4:1 rebound(genius pass Jur...,57:05,NaN,NaN,NaN,NaN,NaN,NaN
14,24.06 - 22:00,Friendly,Lakeside Hoppers,['team_id=39343'],5:2,['match_id=897060558'],HC Jelgava Stars,['team_id=42152']
15,NaN,00:00,Tactical points offense 5 defense 5,NaN,NaN,NaN,NaN,NaN
16,NaN,04:00,penalty player - Juris Norītis4 on 5,NaN,NaN,NaN,NaN,NaN
17,Egor Dzhavadov - 1:0 Counter-attacks(Adam Prac...,06:03,NaN,NaN,NaN,NaN,NaN,NaN
18,penalty player - Josef Široký4 on 5,09:01,NaN,NaN,NaN,NaN,NaN,NaN
19,"Josef Široký - 2:0 (Tobias Vester, Vladimír Pi...",12:47,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,15:00,penalty player - Staņislavs Bullītis4 on 5,NaN,NaN,NaN,NaN,NaN
21,penalty player - Adam Prachkovskiy4 on 5,18:03,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,20:00,Tactical points offense 5 defense 5,NaN,NaN,NaN,NaN,NaN
23,Egor Dzhavadov - 3:0 (Daumants Latvis),22:12,NaN,NaN,NaN,NaN,NaN,NaN
24,penalty player - Tibor Stodola4 on 5,23:56,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,24:31,Cyrille Boulanger - 3:1 PPrebound(unassisted),NaN,NaN,NaN,NaN,NaN
26,NaN,28:48,"Vasile Halip - 3:2 (poor pass Atis Zilgalvis, ...",NaN,NaN,NaN,NaN,NaN
27,Pulling the goalie,30:37,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,33:20,penalty player - Juris Norītis4 on 5,NaN,NaN,NaN,NaN,NaN
29,"Egor Dzhavadov - 4:2 PP (Adam Prachkovskiy, Uģ...",33:29,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1301,Gundars Zikmans - 10:2 (genius pass Filip Chvo...,50:32,NaN,NaN,NaN,NaN,NaN,NaN
1302,Andris Spītnieks - 11:2 Counter-attacks(Martin...,52:20,NaN,NaN,NaN,NaN,NaN,NaN
1303,NaN,53:57,penalty player - Ernests Beļavskis4 on 5,NaN,NaN,NaN,NaN,NaN
1304,NaN,58:18,Folmer Toft - 11:3 (unassisted),NaN,NaN,NaN,NaN,NaN
1305,28.08 - 21:00,Playoff,HC Jelgava Stars,['team_id=42152'],6:2,['match_id=897340456'],Soda Beņķa Sildītāji,['team_id=28975']
1306,Tactical points offense 5 defense 5,00:00,NaN,NaN,NaN,NaN,NaN,NaN
1307,NaN,08:58,penalty player - Andris Spītnieks4 on 5,NaN,NaN,NaN,NaN,NaN
1308,penalty player - Karl LoBianco4 on 5,11:57,NaN,NaN,NaN,NaN,NaN,NaN
1309,penalty player - Edgars Miķelsons4 on 5,14:57,NaN,NaN,NaN,NaN,NaN,NaN
1310,Aggressiveness +1,15:27,NaN,NaN,NaN,NaN,NaN,NaN
1311,NaN,17:58,penalty player - Atvars Plētnieks4 on 5,NaN,NaN,NaN,NaN,NaN
1312,NaN,18:22,penalty player - Gustav Lindblad3 on 5,NaN,NaN,NaN,NaN,NaN
1313,Ernests Beļavskis - 1:0 PP(neat pass Bohuslav ...,19:05,NaN,NaN,NaN,NaN,NaN,NaN
1314,Tactical points offense 5 defense 5,20:00,NaN,NaN,NaN,NaN,NaN,NaN
1315,NaN,26:24,penalty player - Gustav Lindblad4 on 5,NaN,NaN,NaN,NaN,NaN
1316,Atis Zilgalvis - 2:0 PP (Dennis Ivarsson),26:36,NaN,NaN,NaN,NaN,NaN,NaN
1317,NaN,27:44,Jurģis Velns - 2:1 Counter-attacks(genius pass...,NaN,NaN,NaN,NaN,NaN
1318,NaN,30:38,penalty player - Gustav Lindblad4 on 5,NaN,NaN,NaN,NaN,NaN
1319,"Atis Zilgalvis - 3:1 PP(Vasile Halip, Mário Iván)",30:49,NaN,NaN,NaN,NaN,NaN,NaN
1320,Joshua Adams - 4:1 Counter-attacks(excellent p...,34:08,NaN,NaN,NaN,NaN,NaN,NaN
1321,penalty player - Mário Iván4 on 5,36:46,NaN,NaN,NaN,NaN,NaN,NaN
1322,Tactical points offense 5 defense 5,40:00,NaN,NaN,NaN,NaN,NaN,NaN
1323,NaN,47:59,penalty player - Edgars Valters4 on 5,NaN,NaN,NaN,NaN,NaN
1324,"Vasile Halip - 5:1 PP (Dennis Ivarsson, Ilya T...",48:12,NaN,NaN,NaN,NaN,NaN,NaN
1325,Edgars Miķelsons - 6:1 Counter-attacks(unassis...,51:25,NaN,NaN,NaN,NaN,NaN,NaN
1326,penalty player - Atis Zilgalvis4 on 5,52:11,NaN,NaN,NaN,NaN,NaN,NaN
1327,NaN,55:38,Raymond Michel - 6:2 Counter-attacks(perfect p...,NaN,NaN,NaN,NaN,NaN
1328,Pulling the goalie,56:13,NaN,NaN,NaN,NaN,NaN,NaN
1329,penalty player - Staņislavs Bullītis4 on 5,57:15,NaN,NaN,NaN,NaN,NaN,NaN
1330,NaN,60:00,penalty player - Kristijan Pujac4 on 5,NaN,NaN,NaN,NaN,NaN

In [5]:
logfile.describe()

,date,game_type,home_team,h_id,game_result,game_id,away_team,a_id
count,693,1331,705,67,67,67,67,67
unique,477,898,404,32,40,67,27,27
top,Tactical points offense 5 defense 5,20:00,Tactical points offense 5 defense 5,['team_id=42152'],1:4,['match_id=897112414'],HC Jelgava Stars,['team_id=42152']
freq,94,92,110,30,4,1,37,37

### clean logfile from rows which contains strings like - 
    'penalty player',
    'Pulling the goalie',
    'Tactical points offense 5 defense 5',
    'Aggressiveness +1'

In [6]:
tactical = logfile.loc[(logfile['date'] == 'Tactical points offense 5 defense 5') | 
                       (logfile['home_team'] == 'Tactical points offense 5 defense 5')]

In [7]:
logfile = logfile.drop(logfile.index[[tactical.index]])

In [10]:
logfile = logfile.reset_index(drop=True)

In [11]:
pulling = logfile.loc[(logfile['date'] == 'Pulling the goalie') | 
                       (logfile['home_team'] == 'Pulling the goalie')]

In [12]:
logfile = logfile.drop(logfile.index[[pulling.index]])

In [14]:
logfile = logfile.reset_index(drop=True)

In [15]:
aggress = logfile.loc[(logfile['date'] == 'Aggressiveness +1') | 
                       (logfile['home_team'] == 'Aggressiveness +1')]

In [17]:
logfile = logfile.drop(logfile.index[[aggress.index]])
logfile = logfile.reset_index(drop=True)

In [19]:
logfile = logfile[~logfile['date'].str.contains("penalty",na=False)]
logfile = logfile[~logfile['home_team'].str.contains("penalty",na=False)]

In [21]:
logfile = logfile.reset_index(drop=True)

#### cleaned file

In [22]:
logf = logfile[['date','game_type','home_team']]

In [23]:
logf[:5]

,date,game_type,home_team
0,23.06 - 21:00,Friendly,HC Jelgava Stars
1,"Francis Taukulis - 1:0 (Niks Silmacis, Staņisl...",03:09,NaN
2,Lucas McDonald - 2:0 (perfect pass Juris Norītis),20:16,NaN
3,Lucas McDonald - 3:0 PPrebound(poor pass Edmun...,28:04,NaN
4,NaN,52:41,Max Miilunpohja - 3:1 PPrebound(poor pass Panu...

#### Calculate goals and assists for each player and create df

 load csv file to get player names

In [24]:
player_names = pd.read_csv('clean_data/players.csv')
player_names['name'][:3]

0         Vasile Halip
1      Ilya Tonkonogov
2    Cyrille Boulanger
Name: name, dtype: object

### Save to list goal scorers and their assistants
#### away games

In [25]:
some=[]
for i in player_names['name']:
    goals = logf[logf['home_team'].str.startswith(i,na=False)]
    name = goals['home_team'][goals.index].str.split('-',1)
    some.append(name)

In [27]:
some[0]

11     [Vasile Halip ,  3:2 (poor pass Atis Zilgalvis...
151                 [Vasile Halip ,  0:2 (Joshua Adams)]
155    [Vasile Halip ,  0:5 PP(Ilya Tonkonogov, Bohus...
260    [Vasile Halip ,  0:4 PP(Joshua Adams, Bohuslav...
262                   [Vasile Halip ,  0:6 (unassisted)]
404             [Vasile Halip ,  1:1 SH (Karl LoBianco)]
466    [Vasile Halip ,  1:3 Checking(Leroy Sizemore, ...
Name: home_team, dtype: object

#### now create dict with key as player and items as assistants
    - then dict to dataframe

In [28]:
away_g_scorers = {}

In [29]:
for i in range(len(some)):
    for key,value in some[i]:
        if key not in away_g_scorers:
            away_g_scorers[key] = [value]
            type(away_g_scorers[key]) == list
        elif type(away_g_scorers[key]) == list:
            away_g_scorers[key].append(value)
        else:
            away_g_scorers[key] = [away_g_scorers[key], value]

In [30]:
goal_a = pd.DataFrame.from_dict(away_g_scorers,orient='index')

In [32]:
goal_a[:2]

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
Vasile Halip,"3:2 (poor pass Atis Zilgalvis, Jurģis Nagrebis)",0:2 (Joshua Adams),"0:5 PP(Ilya Tonkonogov, Bohuslav Kotrba)","0:4 PP(Joshua Adams, Bohuslav Kotrba)",0:6 (unassisted),1:1 SH (Karl LoBianco),"1:3 Checking(Leroy Sizemore, Karl LoBianco)",None,None,None,...,None,None,None,None,None,None,None,None,None,None
Ilya Tonkonogov,4:4 PP(genius pass Dennis Ivarsson),None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

#### Add pp (powerplay) and sh(shorthanded) goal count at away games, unassisted aswell

In [33]:
goal_a = goal_a.reset_index()

new dict for final away games calculations

In [34]:
fin_a = {}

In [35]:
for i in range(len(goal_a)):
    name = goal_a['index'][i]
    total_goals = goal_a.iloc[i][goal_a.iloc[i].str.contains(':',na=False)].count()
    pp_goals = goal_a.iloc[i][goal_a.iloc[i].str.contains('PP',na=False)].count()
    sh_goals = goal_a.iloc[i][goal_a.iloc[i].str.contains('SH',na=False)].count()
    un_goals = goal_a.iloc[i][goal_a.iloc[i].str.contains('unassisted',na=False)].count()
    
    goals = [pp_goals,sh_goals,un_goals,total_goals]
    if name not in fin_a:
        fin_a[name] = goals

In [39]:
fin_a

{'Vasile Halip ': [2, 1, 1, 7],
 'Ilya Tonkonogov ': [1, 0, 0, 1],
 'Cyrille Boulanger ': [2, 0, 1, 9],
 'Joshua Adams ': [0, 0, 1, 7],
 'Ernests Beļavskis ': [1, 1, 1, 6],
 'Petr Pozhnikov ': [0, 0, 0, 1],
 'Bohuslav Kotrba ': [0, 0, 0, 1],
 'Dennis Ivarsson ': [1, 0, 2, 4],
 'Mário Iván ': [0, 0, 0, 2],
 'Leroy Sizemore ': [0, 0, 0, 2],
 'Maigonis Ušackis ': [4, 0, 1, 9],
 'Folmer Toft ': [5, 0, 5, 21],
 'Atis Zilgalvis ': [7, 0, 1, 14],
 'Vladimirs Znotiņš ': [0, 0, 0, 6],
 'Uvis Vakseris ': [2, 0, 0, 7],
 'Francis Taukulis ': [0, 0, 2, 12],
 'Jurģis Nagrebis ': [1, 0, 0, 6],
 'Alberts Timanovskis ': [0, 0, 1, 6],
 'Staņislavs Bullītis ': [1, 0, 0, 8],
 'Niks Silmacis ': [0, 0, 0, 1],
 'Andris Kraulis ': [0, 0, 0, 2],
 'Edmunds Bambergs ': [1, 0, 0, 4]}

In [40]:
# away_table dataframe for away scoring

In [41]:
away_table = pd.DataFrame.from_dict(fin_a,orient='index',
                                    columns=['Away_pp','Away_sh','A_un','A_goals'])

In [42]:
away_table[:3]

                    Away_pp  Away_sh  A_un  A_goals
Vasile Halip              2        1     1        7
Ilya Tonkonogov           1        0     0        1
Cyrille Boulanger         2        0     1        9

## Home game scorers

the same routine as for away game scorers only take different column ['date'] for calculations

In [43]:
some=[]
for i in player_names['name']:
    goals = logf[logf['date'].str.startswith(i,na=False)]
    name = goals['date'][goals.index].str.split('-',1)
    some.append(name)

In [44]:
home_g_scorers = {}

In [45]:
for i in range(len(some)):
    for key,value in some[i]:
        if key not in home_g_scorers:
            home_g_scorers[key] = [value]
            type(home_g_scorers[key]) == list
        elif type(home_g_scorers[key]) == list:
            home_g_scorers[key].append(value)
        else:
            home_g_scorers[key] = [home_g_scorers[key], value]

In [46]:
goal_sc = pd.DataFrame.from_dict(home_g_scorers,orient='index')

In [49]:
goal_sc = goal_sc.reset_index()

In [50]:
goal_sc[10:12]

,index,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
10,Maigonis Ušackis,4:0 PP(neat pass Petr Pozhnikov),"1:0 (Dennis Ivarsson, Folmer Toft)",4:2 (unassisted),5:2 (Vladimirs Znotiņš),"3:3 (excellent pass Vladimirs Znotiņš, Ilya T...","2:0 (excellent pass Karl LoBianco, Vasile Halip)",2:5 (excellent pass Vladimirs Znotiņš),"7:2 Checking(excellent pass Juris Norītis, Le...","2:1 (excellent pass Vladimirs Znotiņš, Juris ...",4:0 (unassisted),None,None,None,None,None
11,Folmer Toft,"1:0 (Dennis Ivarsson, Maigonis Ušackis)",4:1 Counter-attacks(excellent pass Leroy Size...,5:0 (genius pass Dennis Ivarsson),3:0 PP(Ilya Tonkonogov),6:2 PPrebound(Bohuslav Kotrba),1:0 (unassisted),"1:1 Counter-attacks(Bohuslav Kotrba, Leroy Si...",2:1 (Osvalds Jākabsons),"6:3 PPrebound(perfect pass Jurģis Nagrebis, O...",None,None,None,None,None,None

##### dict for home games

In [51]:
fin_tab = {}

In [52]:
for i in range(0,len(goal_sc)):
    name = goal_sc['index'][i]
    total_goals = goal_sc.iloc[i][goal_sc.iloc[i].str.contains(':',na=False)].count()
    pp_goals = goal_sc.iloc[i][goal_sc.iloc[i].str.contains('PP',na=False)].count()
    sh_goals = goal_sc.iloc[i][goal_sc.iloc[i].str.contains('SH',na=False)].count()
    un_goals = goal_sc.iloc[i][goal_sc.iloc[i].str.contains('unassisted',na=False)].count()
    
    goals = [pp_goals,sh_goals,un_goals,total_goals]
    if name not in fin_tab:
        fin_tab[name] = goals

In [53]:
len(fin_tab)

22

In [54]:
home_table = pd.DataFrame.from_dict(fin_tab,orient='index',columns=['Home_pp','Home_sh','H_un','H_goals'])

In [55]:
home_table[:3]

                    Home_pp  Home_sh  H_un  H_goals
Vasile Halip              5        0     1       10
Ilya Tonkonogov           1        0     0        3
Cyrille Boulanger         0        0     0        7

# concat all goals together

In [144]:
pp_sh_total = pd.concat([home_table,away_table], sort=True, axis=1)

In [145]:
# fill na values with 0
pp_sh_total = pp_sh_total.fillna(0)

In [146]:
pp_sh_total[:3]

,Home_pp,Home_sh,H_un,H_goals,Away_pp,Away_sh,A_un,A_goals
Alberts Timanovskis,0.0,0.0,0.0,3.0,0.0,0.0,1.0,6.0
Andris Kraulis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Atis Zilgalvis,6.0,0.0,2.0,15.0,7.0,0.0,1.0,14.0

In [62]:
#pp_sh_total.sort_values(by=['H_un','A_un'],ascending=False)

# Player assists

#### use previous data

    - goal_sc   for Home games
    - goal_a    for away games

## Home games

### if player assisted more than once than just add +1 to value

In [63]:
home_assists = {}

In [64]:
for i in range(len(goal_sc)):
    for nam in player_names['name']:
        
        counter = goal_sc.iloc[i][goal_sc.iloc[i].str.contains(nam,na=False)].count()
        name = goal_sc['index'][i].strip()
        
        data = [nam,counter]
        
        if name not in home_assists:
            if counter > 0 and name != nam:
                home_assists[name] = [data]
        else:
            if counter > 0 and name != nam:
                home_assists[name].append(data)

In [65]:
home_as = pd.DataFrame.from_dict(home_assists,orient='index')

In [67]:
home_as[:3]

,0,1,2,3,4,5,6,7,8,9,10
Vasile Halip,"[Ilya Tonkonogov, 2]","[Joshua Adams, 2]","[Ernests Beļavskis, 1]","[Karl LoBianco, 1]","[Bohuslav Kotrba, 2]","[Dennis Ivarsson, 1]","[Leroy Sizemore, 1]","[Maigonis Ušackis, 2]","[Jurģis Nagrebis, 1]","[Staņislavs Bullītis, 1]","[Juris Norītis, 2]"
Ilya Tonkonogov,"[Vasile Halip, 1]","[Petr Pozhnikov, 1]","[Bohuslav Kotrba, 1]","[Dennis Ivarsson, 1]","[Mário Iván, 1]",None,None,None,None,None,None
Cyrille Boulanger,"[Joshua Adams, 2]","[Ernests Beļavskis, 1]","[Petr Pozhnikov, 2]","[Edgars Miķelsons, 1]","[Alberts Timanovskis, 1]",None,None,None,None,None,None

### counting total assists for each player (home games)

In [68]:
home_as = home_as.reset_index()

In [69]:
assist_counter = {}

In [70]:
for i in range(len(home_as)):
    for goal in range(len(home_as.iloc[0])):
        for name in player_names['name']:
            try:
                if name in home_as.iloc[i][goal][0]:
                    plr_name = home_as['index'][i]
                    
                    counter = home_as.iloc[i][goal][1]
                    if name not in assist_counter:
                        assist_counter[name] = [counter]
                    elif name in assist_counter:
                        assist_counter[name].append(counter)
            except:
                TypeError

In [71]:
assisters = pd.DataFrame.from_dict(assist_counter,orient='index')

In [73]:
assisters[:3]

                   0    1    2    3    4    5    6   7   8
Ilya Tonkonogov    2  2.0  1.0  1.0  1.0  1.0  1.0 NaN NaN
Joshua Adams       2  2.0  2.0  3.0  2.0  NaN  NaN NaN NaN
Ernests Beļavskis  1  1.0  1.0  2.0  1.0  1.0  NaN NaN NaN

#### count total home assists

In [74]:
assisters['H_assist'] = assisters.sum(axis=1)

In [75]:
assisters = assisters.sort_values(by=['H_assist'],ascending=False)

In [121]:
assisters[:5]

                 H_assist
Dennis Ivarsson      18.0
Juris Norītis        11.0
Joshua Adams         11.0
Petr Pozhnikov       10.0
Ilya Tonkonogov       9.0

# team player assists Away games

### just repeating previous steps, jusing another dataframe (goal_a)

In [78]:
away_assists = {}

In [79]:
for i in range(len(goal_a)):
    for nam in player_names['name']:
        
        counter = goal_a.iloc[i][goal_a.iloc[i].str.contains(nam,na=False)].count()
        name = goal_a['index'][i].strip()
        
        data = [nam,counter]
        
        if name not in away_assists:
            if counter > 0 and name != nam:
                away_assists[name] = [data]
        else:
            if counter > 0 and name != nam:
                away_assists[name].append(data)

In [80]:
away_as = pd.DataFrame.from_dict(away_assists,orient='index')

In [81]:
away_as = away_as.reset_index()

In [82]:
away_as[:3]

,index,0,1,2,3,4,5,6,7,8,9,10
0,Vasile Halip,"[Ilya Tonkonogov, 1]","[Joshua Adams, 2]","[Karl LoBianco, 2]","[Bohuslav Kotrba, 2]","[Leroy Sizemore, 1]","[Atis Zilgalvis, 1]","[Jurģis Nagrebis, 1]",None,None,None,None
1,Ilya Tonkonogov,"[Dennis Ivarsson, 1]",None,None,None,None,None,None,None,None,None,None
2,Cyrille Boulanger,"[Vasile Halip, 2]","[Joshua Adams, 5]","[Petr Pozhnikov, 1]","[Bohuslav Kotrba, 3]","[Dennis Ivarsson, 1]","[Mário Iván, 1]","[Edgars Miķelsons, 1]",None,None,None,None

#### now counting it!

In [83]:
assist_counter_a = {}

In [84]:
for i in range(len(away_as)):
    for goal in range(len(away_as.iloc[0])):
        for name in player_names['name']:
            try:
                if name in away_as.iloc[i][goal][0]:
                    plr_name = away_as['index'][i]
                    
                    counter = away_as.iloc[i][goal][1]
                    if name not in assist_counter_a:
                        assist_counter_a[name] = [counter]
                    elif name in assist_counter:
                        assist_counter_a[name].append(counter)
            except:
                TypeError

In [85]:
assisters_a = pd.DataFrame.from_dict(assist_counter_a,orient='index')

In [86]:
assisters_a['A_assist'] = assisters_a.sum(axis=1)

In [87]:
assisters_a = assisters_a.sort_values(by=['A_assist'],ascending=False)

In [123]:
assisters_a[:5]

                     A_assist
Dennis Ivarsson          29.0
Joshua Adams             15.0
Ilya Tonkonogov          11.0
Bohuslav Kotrba          11.0
Alberts Timanovskis      11.0

In [93]:
print(len(assisters_a))
print(len(assisters))

25
27

#### need only 1 column from each assists dataframes
    - assisters['H_assist']
    - assisters_a['A_assist']

In [96]:
assisters = assisters['H_assist']
assisters_a = assisters_a['A_assist']

In [104]:
# need convert to frame for merging

In [105]:
assisters = assisters.to_frame()
assisters_a = assisters_a.to_frame()

In [124]:
total_assists = assisters.join(assisters_a, how='outer')

In [128]:
total_assists[:4]

                     H_assist  A_assist
Alberts Timanovskis       6.0      11.0
Andris Kraulis            2.0       4.0
Atis Zilgalvis            4.0       5.0
Bohuslav Kotrba           9.0      11.0

## now create dataframe with all previous data!

    pp_sh_total    --- scored goals
    total_assists  --- assists made

In [147]:
pp_sh_total.index = pp_sh_total.index.str.strip()

In [130]:
len(total_assists)

27

In [148]:
final_scoring_table = total_assists.join(pp_sh_total, how='outer')

#### or can merge, but further will use final_scoring_table

In [154]:
#df_merged = pp_sh_total.merge(total_assists, how='outer', left_index=True, right_index=True)

### add total columns for:
    assists,
    goals,
    points

In [153]:
final_scoring_table = final_scoring_table.fillna(0)

In [155]:
final_scoring_table['Total_asists'] = final_scoring_table['A_assist'] + final_scoring_table['H_assist']
final_scoring_table['Total_goals'] = final_scoring_table['A_goals'] + final_scoring_table['H_goals']

In [157]:
final_scoring_table['Total_points'] = final_scoring_table['Total_goals'] + final_scoring_table['Total_asists']

In [158]:
final_scoring_table[:3]

,H_assist,A_assist,Home_pp,Home_sh,H_un,H_goals,Away_pp,Away_sh,A_un,A_goals,Total_asists,Total_goals,Total_points
Alberts Timanovskis,6.0,11.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,6.0,17.0,9.0,26.0
Andris Kraulis,2.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,2.0,8.0
Atis Zilgalvis,4.0,5.0,6.0,0.0,2.0,15.0,7.0,0.0,1.0,14.0,9.0,29.0,38.0

In [161]:
final_scoring_table = final_scoring_table.sort_values(by=['Total_points','Total_goals'],ascending=False)

#### save csv file season_scoring inlcuding only:
    - Total_asists
    - Total_goals
    - Total_points

In [162]:
season_scoring = final_scoring_table[['Total_asists', 'Total_goals','Total_points']]

In [166]:
season_scoring.reset_index().to_csv('clean_data/season_scoring.csv')

In [167]:
season_scoring[:5]

                 Total_asists  Total_goals  Total_points
Dennis Ivarsson          47.0          8.0          55.0
Joshua Adams             26.0         14.0          40.0
Atis Zilgalvis            9.0         29.0          38.0
Folmer Toft               2.0         30.0          32.0
Vasile Halip             11.0         17.0          28.0